a="""disconnectXFromY :: DisconnectXFromY
      , destroyUnit :: DestroyUnit
      , makeAllpass :: MakeAllpass
      , makeAnalyser :: MakeAnalyser
      , makeAudioWorkletNode :: MakeAudioWorkletNode
      , makeBandpass :: MakeBandpass
      , makeConstant :: MakeConstant
      , makePassthroughConvolver :: MakePassthroughConvolver
      , makeConvolver :: MakeConvolver
      , makeDelay :: MakeDelay
      , makeDynamicsCompressor :: MakeDynamicsCompressor
      , makeGain :: MakeGain
      , makeHighpass :: MakeHighpass
      , makeHighshelf :: MakeHighshelf
      , makeInput :: MakeInput
      , makeLoopBuf :: MakeLoopBuf
      , makeLoopBufWithDeferredBuffer :: MakeLoopBufWithDeferredBuffer
      , makeLowpass :: MakeLowpass
      , makeLowshelf :: MakeLowshelf
      , makeMicrophone :: MakeMicrophone
      , makeNotch :: MakeNotch
      , makePeaking :: MakePeaking
      , makePeriodicOscWithDeferredOsc :: MakePeriodicOscWithDeferredOsc
      , makePeriodicOsc :: MakePeriodicOsc
      , makePlayBuf :: MakePlayBuf
      , makePlayBufWithDeferredBuffer :: MakePlayBufWithDeferredBuffer
      , makeRecorder :: MakeRecorder
      , makeSawtoothOsc :: MakeSawtoothOsc
      , makeSinOsc :: MakeSinOsc
      , makeSquareOsc :: MakeSquareOsc
      , makeSpeaker :: Unit
      , makeStereoPanner :: MakeStereoPanner
      , makeTriangleOsc :: MakeTriangleOsc
      , makeWaveShaper :: MakeWaveShaper
      , makeSubgraph :: MakeSubgraph
      , makeSubgraphWithDeferredScene :: MakeSubgraphWithDeferredScene
      , makeTumult :: MakeTumult
      , makeTumultWithDeferredGraph :: MakeTumultWithDeferredGraph
      , connectXToY :: ConnectXToY
      , setAnalyserNodeCb :: SetAnalyserNodeCb
      , setMediaRecorderCb :: SetMediaRecorderCb
      , setAudioWorkletParameter :: SetAudioWorkletParameter
      , setBuffer :: SetBuffer
      , setConvolverBuffer :: SetConvolverBuffer
      , setPeriodicOsc :: SetPeriodicOsc
      , setOnOff :: SetOnOff
      , setBufferOffset :: SetBufferOffset
      , setLoopStart :: SetLoopStart
      , setLoopEnd :: SetLoopEnd
      , setRatio :: SetRatio
      , setOffset :: SetOffset
      , setAttack :: SetAttack
      , setGain :: SetGain
      , setQ :: SetQ
      , setPan :: SetPan
      , setThreshold :: SetThreshold
      , setRelease :: SetRelease
      , setKnee :: SetKnee
      , setDelay :: SetDelay
      , setPlaybackRate :: SetPlaybackRate
      , setFrequency :: SetFrequency
      , setWaveShaperCurve :: SetWaveShaperCurve
      , setInput :: SetInput
      , setSubgraph :: SetSubgraph
      , setTumult :: SetTumult"""

a = [[y.strip() for y in x.strip().replace(',','').split('::')] for x in a.split('\n')]
for x in a:
  if 'set' in x[0]:
    print('  , %s: %s' % (x[0],x[0]))
